// <auto-generated />
using System;
using Hanseatic_Dealings_API.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HanseaticDealingsAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hanseatic_Dealings_API.Models.CityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xcord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ycord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hanseatic_Dealings_API.Models.CityStorageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityModelId")
                        .HasColumnType("int");

                    b.Property<int>("Current")
                        .HasColumnType("int");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<int>("Limit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityModelId");

                    b.ToTable("CityStorageModel");
                });

            modelBuilder.Entity("Hanseatic_Dealings_API.Models.ShipModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Hanseatic_Dealings_API.Models.ShipStorageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<int?>("ShipModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipModelId");

                    b.ToTable("ShipStorageModel");
                });

            modelBuilder.Entity("Hanseatic_Dealings_API.Models.CityStorageModel", b =>
                {
                    b.HasOne("Hanseatic_Dealings_API.Models.CityModel", null)
                        .WithMany("Goods")
                        .HasForeignKey("CityModelId");
                });

            modelBuilder.Entity("Hanseatic_Dealings_API.Models.ShipStorageModel", b =>
                {
                    b.HasOne("Hanseatic_Dealings_API.Models.ShipModel", null)
                        .WithMany("Goods")
                        .HasForeignKey("ShipModelId");
                });

            modelBuilder.Entity("Hanseatic_Dealings_API.Models.CityModel", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("Hanseatic_Dealings_API.Models.ShipModel", b =>
                {
                    b.Navigation("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
